# Generated by Django 3.2 on 2023-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230513_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='Нет описания', max_length=1000, verbose_name='Описание произведения'),
        ),
    ]
